services:
  python-flask-api:
    build: .
    image: python-flask-api:dev
    container_name: python-flask-api
    ports:
      - '5005:5005'
    volumes:
      - .:/app
    depends_on:
      - python-flask-db
      - dotnet-document-generator
    env_file:
      - ./.env
    networks:
      main:
        aliases:
          - python-flask-api
  python-flask-db:
    image: postgres:15
    container_name: python-flask-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Chr0me#1
      - POSTGRES_DB=flask_test_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - python-flask-db
  dotnet-document-generator:
    build:
      context: document_api/
    image: dotnet-document-generator:dev
    container_name: dotnet-document-generator
    ports: 
      - '8080:8080'
    env_file:
      - document_api/.env
    platform: linux/amd64
    networks:
      main:
        aliases:
          - dotnet-document-generator

networks:
  main:
  
volumes:
  postgres_data:
