services:
  python-flask-api:
    build: .
    image: python-flask-api:dev
    container_name: python-flask-api
    ports:
      - '5005:5005'
    volumes:
      - .:/app
    depends_on:
      - python-flask-db
    env_file:
      - ./.env
  python-flask-db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Chr0me#1
      - POSTGRES_DB=flask_test_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
