"""empty message

Revision ID: 814549ef57ce
Revises: 9ddba713629e
Create Date: 2026-03-16 23:22:19.842533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814549ef57ce'
down_revision = '9ddba713629e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('validated')

    # ### end Alembic commands ###
