"""Add revenue column

Revision ID: 4cb6f805f94e
Revises: 2c47b05dbd7f
Create Date: 2026-06-11 02:54:45.521256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb6f805f94e'
down_revision: Union[str, Sequence[str], None] = '2c47b05dbd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revenue', sa.Column('revenue', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revenue', 'revenue')
    # ### end Alembic commands ###
