"""add is_admin column

Revision ID: c67f0440d0f8
Revises: c0b220a8a5a7
Create Date: 2026-04-22 01:15:22.431637

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c67f0440d0f8"
down_revision: Union[str, Sequence[str], None] = "c0b220a8a5a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "item",
        "price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_admin")
    op.alter_column(
        "item",
        "price",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
