"""Add

Revision ID: d2f1d87d3cfb
Revises: c67f0440d0f8
Create Date: 2026-06-11 01:37:10.542144

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2f1d87d3cfb"
down_revision: Union[str, Sequence[str], None] = "c67f0440d0f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "item",
        "price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.add_column("user", sa.Column("name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "name")
    op.alter_column(
        "item",
        "price",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
