"""deleted price column

Revision ID: f0f4bdbce536
Revises: 607710972483
Create Date: 2026-06-11 02:06:16.435841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f4bdbce536'
down_revision: Union[str, Sequence[str], None] = '607710972483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('price', sa.REAL(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
